spring:
  data:
    mongodb:
      uri: mongodb://myUserAdmin:abc123@localhost:27017/?authSource=admin
      database: booking
logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG